"""Quest catalog: 6 quests × 15 questions each."""

from __future__ import annotations

from typing import Any

QuestQuestion = dict[str, Any]
QuestCategory = dict[str, Any]


def _chart(spec: tuple[str, str, str, str]) -> dict[str, str]:
    ctype, x, y, title = spec
    return {"type": ctype, "x": x, "y": y, "title": title}


def _q(
    qid: str,
    text: str,
    sql_file: str,
    *,
    metrics: list[tuple[str, str, str, str]],
    chart: tuple[str, str, str, str] | None = None,
    chart2: tuple[str, str, str, str] | None = None,
    product: str = "",
    finance: str = "",
    analyst: str = "",
) -> QuestQuestion:
    return {
        "id": qid,
        "text": text,
        "sql_file": sql_file,
        "metrics": [
            {"label": label, "column": col, "agg": agg, "format": fmt}
            for label, col, agg, fmt in metrics
        ],
        "chart": _chart(chart) if chart else None,
        "chart2": _chart(chart2) if chart2 else None,
        "recommendations": {"product": product, "finance": finance, "analyst": analyst},
    }


QUEST_CATEGORIES: list[QuestCategory] = [
    {
        "id": "revenue_growth",
        "title": "Revenue & Growth",
        "icon": "📈",
        "lens": "Finance / Analyst",
        "description": "How sales change over time, and where money is lost before an order is delivered.",
        "questions": [
            _q("rg01", "How does monthly GMV trend over time?", "revenue_growth/01_monthly_gmv.sql",
               metrics=[("Total GMV", "gmv", "sum", "currency"), ("Total Orders", "orders", "sum", "int"), ("Peak Month GMV", "gmv", "max", "currency")],
               chart=("line", "purchase_month", "gmv", "Monthly GMV"), chart2=("bar", "purchase_month", "orders", "Monthly Orders"),
               product="Double down on peak-season campaigns when GMV spikes.", finance="Use GMV trend for cash-flow forecasting.", analyst="Validate month grain before MoM comparisons."),
            _q("rg02", "What is the month-over-month GMV growth rate?", "revenue_growth/02_mom_growth.sql",
               metrics=[("Latest MoM Growth", "mom_growth_pct", "last", "pct"), ("Best Growth Month", "mom_growth_pct", "max", "pct"), ("Avg MoM Growth", "mom_growth_pct", "mean", "pct")],
               chart=("line", "purchase_month", "mom_growth_pct", "MoM GMV Growth %"),
               product="Invest in retention when growth decelerates.", finance="Flag negative MoM early for revenue risk.", analyst="First month has null growth — exclude from averages."),
            _q("rg03", "How does average order value change monthly?", "revenue_growth/03_monthly_aov.sql",
               metrics=[("Overall AOV", "avg_order_value", "mean", "currency"), ("Highest AOV Month", "avg_order_value", "max", "currency"), ("Lowest AOV Month", "avg_order_value", "min", "currency")],
               chart=("line", "purchase_month", "avg_order_value", "Average Order Value"),
               product="Bundle offers when AOV dips.", finance="AOV drives revenue more than order count in mature months.", analyst="Compare AOV with discount/payment mix."),
            _q("rg04", "What is the split between product revenue and freight?", "revenue_growth/04_revenue_split.sql",
               metrics=[("Product Revenue", "product_revenue", "sum", "currency"), ("Freight Revenue", "freight_revenue", "sum", "currency"), ("Freight Share", "freight_share_pct", "mean", "pct")],
               chart=("bar", "purchase_month", "product_revenue", "Product vs Freight (monthly)"),
               product="Free-shipping tests if freight share is high.", finance="Freight affects margin reporting separately.", analyst="Freight share spikes may reflect distant states."),
            _q("rg05", "Which states generate the most revenue?", "revenue_growth/05_revenue_by_state.sql",
               metrics=[("Top State Revenue", "revenue", "max", "currency"), ("States Covered", "customer_state", "count", "int"), ("Top State Share", "revenue_share_pct", "max", "pct")],
               chart=("bar", "customer_state", "revenue", "Revenue by State"),
               product="Regional campaigns in top 3 states.", finance="Forecast demand by state cluster.", analyst="Check if concentration creates supply risk."),
            _q("rg06", "Which month had the highest order volume?", "revenue_growth/06_peak_orders.sql",
               metrics=[("Peak Month Orders", "orders", "max", "int"), ("Peak Month GMV", "gmv", "max", "currency"), ("Months Tracked", "purchase_month", "count", "int")],
               chart=("bar", "purchase_month", "orders", "Orders by Month"),
               product="Staff logistics for peak order months.", finance="Align inventory budget with order peaks.", analyst="Cross-check peak with marketing calendar."),
            _q("rg07", "Do weekdays or weekends drive more orders?", "revenue_growth/07_weekday_weekend.sql",
               metrics=[("Weekday Orders", "orders", "first", "int"), ("Weekend Orders", "orders", "last", "int"), ("Weekend Share", "order_share_pct", "last", "pct")],
               chart=("bar", "day_type", "orders", "Weekday vs Weekend Orders"),
               product="Schedule push notifications on high-conversion days.", finance="Weekend spikes may affect cash settlement timing.", analyst="Use purchase timestamp timezone consistently."),
            _q("rg08", "What share of GMV comes from the top 10% of orders?", "revenue_growth/08_gmv_concentration.sql",
               metrics=[("Top 10% GMV Share", "top_decile_gmv_share_pct", "first", "pct"), ("Total GMV", "total_gmv", "first", "currency"), ("Order Count", "total_orders", "first", "int")],
               chart=("bar", "segment", "gmv", "GMV Concentration"),
               product="VIP program for high-value order cohort.", finance="Revenue heavily tied to whale orders if share >40%.", analyst="Concentration metric uses order-level GMV ranks."),
            _q("rg09", "What is the cumulative GMV curve by month?", "revenue_growth/09_cumulative_gmv.sql",
               metrics=[("Final Cumulative GMV", "cumulative_gmv", "last", "currency"), ("Months to 50% GMV", "months_to_half", "first", "int"), ("Latest Month GMV", "monthly_gmv", "last", "currency")],
               chart=("line", "purchase_month", "cumulative_gmv", "Cumulative GMV"),
               product="Measure impact of launches on cumulative slope.", finance="Run-rate projections from cumulative curve.", analyst="Cumulative sums should match total GMV."),
            _q("rg10", "How do order count and GMV correlate monthly?", "revenue_growth/10_orders_gmv_corr.sql",
               metrics=[("Avg Monthly Orders", "orders", "mean", "int"), ("Avg Monthly GMV", "gmv", "mean", "currency"), ("Correlation", "orders_gmv_corr", "first", "float")],
               chart=("line", "purchase_month", "gmv", "GMV vs Orders (dual trend)"), chart2=("line", "purchase_month", "orders", "Order Volume"),
               product="If orders rise but GMV flat, promote upsells.", finance="Decouple volume vs ticket-size drivers.", analyst="Correlation computed across monthly aggregates."),
            _q("rg11", "How fast is delivered GMV growing month over month?", "revenue_growth/11_mom_delivered_gmv.sql",
               metrics=[("Latest MoM Growth", "mom_growth_pct", "last", "pct"), ("Peak Delivered GMV", "delivered_gmv", "max", "currency"), ("Avg MoM Growth", "mom_growth_pct", "mean", "pct")],
               chart=("line", "purchase_month", "mom_growth_pct", "Delivered GMV Growth %"),
               product="Scale campaigns in months where delivered GMV accelerates.", finance="Forecast recognized revenue off delivered GMV, not gross orders.", analyst="LAG window on monthly delivered GMV; first month growth is null."),
            _q("rg12", "What share of purchases actually get delivered each month?", "revenue_growth/12_delivery_conversion.sql",
               metrics=[("Latest Conversion", "conversion_pct", "last", "pct"), ("Avg Conversion", "conversion_pct", "mean", "pct"), ("Total Orders", "orders", "sum", "int")],
               chart=("line", "purchase_month", "conversion_pct", "Purchase-to-Delivery Conversion"),
               product="A falling conversion rate is a delivery promise problem, not a traffic problem.", finance="Undelivered orders should not be treated as earned revenue.", analyst="Conversion = delivered timestamp / orders that month."),
            _q("rg13", "Where is GMV lost in the delivery drop-off funnel?", "revenue_growth/13_gmv_dropoff.sql",
               metrics=[("GMV Lost", "gmv_lost", "sum", "currency"), ("Orders Lost", "orders_lost", "sum", "int"), ("Biggest Leak", "gmv_lost", "max", "currency")],
               chart=("bar", "dropoff_stage", "gmv_lost", "GMV Lost by Drop-off Stage"),
               product="Fix the stage with the largest GMV leak first.", finance="This is revenue sitting before delivery.", analyst="Stages are mutually exclusive: never approved, not shipped, not delivered."),
            _q("rg14", "How much monthly GMV comes from repeat vs new customers?", "revenue_growth/14_new_vs_repeat_gmv.sql",
               metrics=[("Latest Repeat Share", "repeat_share_pct", "last", "pct"), ("Repeat GMV", "repeat_gmv", "sum", "currency"), ("New GMV", "new_gmv", "sum", "currency")],
               chart=("line", "purchase_month", "repeat_share_pct", "Repeat GMV Share"),
               product="If repeat share stays tiny, acquisition is carrying the business.", finance="Repeat GMV is cheaper revenue than first-order GMV.", analyst="Repeat uses customer_unique_id, not the per-order customer_id."),
            _q("rg15", "Is repeat-customer revenue growing month over month?", "revenue_growth/15_repeat_gmv_growth.sql",
               metrics=[("Latest Repeat Growth", "mom_growth_pct", "last", "pct"), ("Total Repeat GMV", "repeat_gmv", "sum", "currency"), ("Best Growth Month", "mom_growth_pct", "max", "pct")],
               chart=("line", "purchase_month", "mom_growth_pct", "Repeat GMV MoM Growth"),
               product="Put retention budget where repeat GMV growth stalls.", finance="Repeat GMV growth is the retention P&L.", analyst="Early months can be null or spiky because the repeat base is small."),

        ],
    },
    {
        "id": "product_categories",
        "title": "Product & Categories",
        "icon": "🛍️",
        "lens": "Product / Finance",
        "description": "Which product types sell, get bought again, or fail to arrive.",
        "questions": [
            _q("pc01", "Which categories drive the most revenue?", "product_categories/01_top_categories_revenue.sql",
               metrics=[("Top Category Revenue", "revenue", "max", "currency"), ("Categories", "category", "count", "int"), ("Top Category Share", "revenue_share_pct", "max", "pct")],
               chart=("bar", "category", "revenue", "Top Categories by Revenue"),
               product="Feature top categories on homepage.", finance="Category mix affects margin planning.", analyst="Use English category names via translation join."),
            _q("pc02", "Which categories get the most orders?", "product_categories/02_top_categories_orders.sql",
               metrics=[("Top Category Orders", "orders", "max", "int"), ("Total Orders", "orders", "sum", "int")],
               chart=("bar", "category", "orders", "Orders by Category"),
               product="High-order/low-revenue categories need basket-building.", finance="Volume leaders may differ from revenue leaders.", analyst="Count distinct order_id to avoid item double-count."),
            _q("pc03", "Which categories have the highest AOV?", "product_categories/03_category_aov.sql",
               metrics=[("Highest Category AOV", "avg_order_value", "max", "currency"), ("Lowest Category AOV", "avg_order_value", "min", "currency")],
               chart=("bar", "category", "avg_order_value", "AOV by Category"),
               product="Cross-sell low-AOV categories with bundles.", finance="Premium categories improve blended AOV.", analyst="AOV here is item-level GMV average per category."),
            _q("pc04", "How many items are sold per order by category?", "product_categories/04_items_per_order.sql",
               metrics=[("Max Items/Order", "avg_items_per_order", "max", "float"), ("Overall Avg Items/Order", "avg_items_per_order", "mean", "float")],
               chart=("bar", "category", "avg_items_per_order", "Avg Items per Order"),
               product="Multi-item promotions for low basket-size categories.", finance="Higher items/order reduces per-order logistics cost.", analyst="Grouped at order-category grain."),
            _q("pc05", "Which categories grew fastest in the latest 6 months?", "product_categories/05_category_growth.sql",
               metrics=[("Fastest Growth Category", "growth_pct", "max", "pct"), ("Categories Analyzed", "category", "count", "int")],
               chart=("bar", "category", "growth_pct", "Category Growth %"),
               product="Scale marketing for fastest-growing categories.", finance="Growth categories drive next-quarter forecast.", analyst="Compare first vs last 3 months in window."),
            _q("pc06", "Which categories underperform on revenue share?", "product_categories/06_bottom_categories.sql",
               metrics=[("Lowest Share Category", "revenue_share_pct", "min", "pct"), ("Bottom-5 Revenue", "revenue", "sum", "currency")],
               chart=("bar", "category", "revenue_share_pct", "Bottom Categories"),
               product="Delist or discount long-tail underperformers.", finance="Reduce inventory carrying cost on low-share SKUs.", analyst="Tail categories may still have strategic value."),
            _q("pc07", "What is freight revenue by category?", "product_categories/07_freight_by_category.sql",
               metrics=[("Highest Freight Category", "freight_revenue", "max", "currency"), ("Total Freight", "freight_revenue", "sum", "currency")],
               chart=("bar", "category", "freight_revenue", "Freight by Category"),
               product="Shipping promos on high-freight categories.", finance="Freight burden affects net margin by category.", analyst="Heavy/bulky products often dominate freight."),
            _q("pc08", "Do products with more photos sell more?", "product_categories/08_photos_vs_sales.sql",
               metrics=[("Best Photo Bucket Revenue", "revenue", "max", "currency"), ("Photo Buckets", "photo_bucket", "count", "int")],
               chart=("bar", "photo_bucket", "revenue", "Revenue by Photo Count"),
               product="Mandate min photo count for seller listings.", finance="Better listings reduce return rates.", analyst="Proxy metric — not causal without experiment."),
            _q("pc09", "Which categories are most popular in each top state?", "product_categories/09_category_by_state.sql",
               metrics=[("State-Category Pairs", "category", "count", "int"), ("Top Pair Revenue", "revenue", "max", "currency")],
               chart=("bar", "category", "revenue", "Top Category Mix (top states)"),
               product="Localized category merchandising.", finance="Regional demand shapes inventory allocation.", analyst="Filtered to top 5 states by revenue."),
            _q("pc10", "What is the price distribution by category?", "product_categories/10_price_distribution.sql",
               metrics=[("Highest Median Price", "median_price", "max", "currency"), ("Lowest Median Price", "median_price", "min", "currency")],
               chart=("bar", "category", "median_price", "Median Price by Category"),
               product="Price-tier badges help customer navigation.", finance="Price bands inform discount policy.", analyst="Median reduces outlier skew vs mean."),
            _q("pc11", "Which categories lose the most orders before delivery?", "product_categories/11_category_dropoff.sql",
               metrics=[("Worst Drop-off", "dropoff_pct", "max", "pct"), ("Categories Shown", "category", "count", "int")],
               chart=("bar", "category", "dropoff_pct", "Category Delivery Drop-off"),
               product="Pause ads on categories that fail delivery.", finance="Drop-off here is lost category revenue.", analyst="Limited to categories with at least 200 orders."),
            _q("pc12", "Which categories have the highest repeat-purchase rate?", "product_categories/12_category_repeat.sql",
               metrics=[("Best Repeat Rate", "repeat_rate_pct", "max", "pct"), ("Avg Repeat Rate", "repeat_rate_pct", "mean", "pct")],
               chart=("bar", "category", "repeat_rate_pct", "Repeat Rate by Category"),
               product="Build replenishment nudges for high-repeat categories.", finance="Repeat categories support a higher CAC.", analyst="A repeat is 2+ orders in the same category by the same person."),
            _q("pc13", "Which categories grew fastest in the latest quarter?", "product_categories/13_category_quarter_growth.sql",
               metrics=[("Fastest Growth", "growth_pct", "max", "pct"), ("Categories Shown", "category", "count", "int")],
               chart=("bar", "category", "growth_pct", "Quarterly Category Growth"),
               product="Feature the fastest-growing categories next quarter.", finance="Use this mix shift in the next revenue forecast.", analyst="Compares Jun-Aug 2018 with Mar-May 2018, prior GMV at least R$8k."),
            _q("pc14", "What do the top 20% high-value customers buy?", "product_categories/14_top20_categories.sql",
               metrics=[("Top Category Revenue", "revenue", "max", "currency"), ("Listed Category Revenue", "revenue", "sum", "currency")],
               chart=("bar", "category", "revenue", "Top 20% Cohort — Categories"),
               product="Merchandize the homepage for this cohort, not the average buyer.", finance="This basket is where high-value GMV concentrates.", analyst="Top 20% = monetary NTILE score 5, joined back to items."),
            _q("pc15", "Which categories convert from order to delivery the worst?", "product_categories/15_category_delivery_conversion.sql",
               metrics=[("Lowest Conversion", "delivery_conversion_pct", "min", "pct"), ("Delivered GMV", "delivered_gmv", "sum", "currency")],
               chart=("bar", "category", "delivery_conversion_pct", "Delivery Conversion by Category"),
               product="Treat low conversion as an ops issue before adding more SKUs.", finance="Ordered GMV overstates what the category actually delivers.", analyst="Sorted ascending so the worst converters are first."),

        ],
    },
    {
        "id": "customer_analytics",
        "title": "Customer Analytics",
        "icon": "👥",
        "lens": "Product / Analyst",
        "description": "Who the best customers are, who comes back, and who is going quiet.",
        "questions": [
            _q("ca01", "How much GMV comes from one-time vs repeat customers?", "customer_analytics/01_customer_segments.sql",
               metrics=[("Loyal Segment GMV", "segment_gmv", "max", "currency"), ("One-Time Customers", "customers", "first", "int")],
               chart=("bar", "customer_segment", "segment_gmv", "GMV by Segment"),
               product="Win-back flow for one-time buyers.", finance="Repeat customers usually have lower CAC payback.", analyst="Segments based on order count buckets."),
            _q("ca02", "What does the customer lifetime GMV distribution look like?", "customer_analytics/02_ltv_distribution.sql",
               metrics=[("Median LTV", "lifetime_gmv", "median", "currency"), ("P90 LTV", "lifetime_gmv", "p90", "currency"), ("Customers", "lifetime_gmv", "count", "int")],
               chart=("bar", "ltv_bucket", "customers", "Customers by LTV Bucket"),
               product="Tier loyalty benefits above P90.", finance="LTV distribution drives CAC tolerance.", analyst="Bucketed for histogram readability."),
            _q("ca03", "Who are the top 20 customers by lifetime GMV?", "customer_analytics/03_top_customers.sql",
               metrics=[("Top Customer GMV", "lifetime_gmv", "max", "currency"), ("Top 20 Total GMV", "lifetime_gmv", "sum", "currency")],
               chart=("bar", "customer_rank", "lifetime_gmv", "Top Customers"),
               product="Concierge support for top accounts.", finance="Whale customers need fraud monitoring too.", analyst="Ranked by lifetime_gmv descending."),
            _q("ca04", "How many orders do most customers place?", "customer_analytics/04_orders_per_customer.sql",
               metrics=[("Single-Order Customers", "customers", "first", "int"), ("5+ Order Customers", "customers", "last", "int")],
               chart=("bar", "order_bucket", "customers", "Customers by Order Count"),
               product="Second-order incentive for single-order users.", finance="Repeat rate is a leading indicator of profitability.", analyst="Buckets: 1, 2-3, 4-5, 6+."),
            _q("ca05", "How many new customers join each month?", "customer_analytics/05_new_customers.sql",
               metrics=[("Peak New Customers", "new_customers", "max", "int"), ("Total New Customers", "new_customers", "sum", "int")],
               chart=("line", "cohort_month", "new_customers", "New Customers per Month"),
               product="Align acquisition spend with new-customer peaks.", finance="New customer cohort size feeds growth models.", analyst="First order month defines new customer."),
            _q("ca06", "What is repeat purchase rate by first-order cohort?", "customer_analytics/06_repeat_rate_cohort.sql",
               metrics=[("Best Cohort Repeat Rate", "repeat_rate_pct", "max", "pct"), ("Avg Repeat Rate", "repeat_rate_pct", "mean", "pct")],
               chart=("bar", "cohort_month", "repeat_rate_pct", "Repeat Rate by Cohort"),
               product="Investigate cohorts with low repeat rates.", finance="Repeat rate impacts CLTV projections.", analyst="Repeat = more than 1 order lifetime."),
            _q("ca07", "How does cohort retention decay over months?", "customer_analytics/07_cohort_retention.sql",
               metrics=[("Month-0 Retention", "retention_pct", "max", "pct"), ("Lowest Retention", "retention_pct", "min", "pct")],
               chart=("line", "months_since_first_order", "retention_pct", "Retention Curve"),
               product="Fix drop between month 0 and 1 first.", finance="Retention curve informs revenue run-rate.", analyst="Classic cohort retention matrix aggregated."),
            _q("ca08", "How long until a customer's second order?", "customer_analytics/08_time_to_second_order.sql",
               metrics=[("Median Days to 2nd Order", "days_to_second", "median", "int"), ("Within 30 Days", "customers", "first", "int")],
               chart=("bar", "days_bucket", "customers", "Days to Second Order"),
               product="Send reminder at day 14 if no second order.", finance="Faster second order = higher CLTV.", analyst="Only customers with 2+ orders included."),
            _q("ca09", "Which states have the most customers?", "customer_analytics/09_customers_by_state.sql",
               metrics=[("Top State Customers", "customers", "max", "int"), ("States", "customer_state", "count", "int")],
               chart=("bar", "customer_state", "customers", "Customers by State"),
               product="Geo-targeted ads in dense states.", finance="Customer base size ≠ revenue size.", analyst="Unique customer_id per state."),
            _q("ca10", "How many customers haven't ordered in 6+ months?", "customer_analytics/10_churn_proxy.sql",
               metrics=[("Churned Proxy Count", "customers", "first", "int"), ("Churn Rate", "churn_rate_pct", "first", "pct"), ("Active Customers", "customers", "last", "int")],
               chart=("bar", "status", "customers", "Active vs Churned Proxy"),
               product="Reactivation campaign for dormant users.", finance="Churn reduces forward revenue base.", analyst="Churn proxy = no order in 180 days."),
            _q("ca11", "How are customers distributed across RFM scores?", "customer_analytics/11_rfm_distribution.sql",
               metrics=[("Customers Scored", "customers", "sum", "int"), ("Highest Score Band", "rfm_score", "max", "int"), ("Top Band GMV", "gmv", "max", "currency")],
               chart=("bar", "rfm_score", "customers", "Customers by RFM Score"),
               product="Use the score, not a single average, to pick who gets which message.", finance="Higher scores concentrate a disproportionate share of GMV.", analyst="R, F, and M are NTILE(5) window scores. RFM score = R + F + M (3 to 15)."),
            _q("ca12", "How much GMV does the top 20% high-value cohort contribute?", "customer_analytics/12_top20_cohort.sql",
               metrics=[("Top 20% GMV Share", "gmv_share_pct", "first", "pct"), ("Top 20% Customers", "customers", "first", "int"), ("Top 20% GMV", "gmv", "first", "currency")],
               chart=("bar", "cohort", "gmv", "GMV: Top 20% vs Other 80%"),
               product="Build a separate retention track for this cohort.", finance="This is the revenue at risk if high-value customers go quiet.", analyst="Top 20% is monetary quintile 5 from NTILE, not a hand-picked list."),
            _q("ca13", "Which RFM segments should retention campaigns target?", "customer_analytics/13_rfm_segments.sql",
               metrics=[("Largest Segment", "customers", "max", "int"), ("Segment GMV", "gmv", "sum", "currency"), ("Segments", "segment", "count", "int")],
               chart=("bar", "segment", "gmv", "GMV by RFM Segment"),
               product="Message At Risk and Hibernating differently from Champions.", finance="At Risk is high monetary value with stale recency — protect it first.", analyst="Segment rules sit on top of the 1-5 R/F/M scores."),
            _q("ca14", "What is month-over-month customer retention?", "customer_analytics/14_mom_retention.sql",
               metrics=[("Latest Retention", "mom_retention_pct", "last", "pct"), ("Best Retention", "mom_retention_pct", "max", "pct"), ("Avg Retention", "mom_retention_pct", "mean", "pct")],
               chart=("line", "month", "mom_retention_pct", "Month-over-Month Retention"),
               product="A retention dip is the trigger for a win-back campaign that month.", finance="MoM retention is the leading indicator for next month's repeat GMV.", analyst="Retained = ordered this month and last month, using customer_unique_id."),
            _q("ca15", "How much high-value GMV is going quiet?", "customer_analytics/15_lapsing_high_value.sql",
               metrics=[("High-Value Customers", "customers", "sum", "int"), ("Lapsed High-Value GMV", "gmv", "last", "currency"), ("Watchlist Customers", "customers", "max", "int")],
               chart=("bar", "recency_bucket", "customers", "Top 20% by Recency"),
               product="Start with the 91-180 day bucket before they hit 180+.", finance="Lapsed GMV is the retention opportunity, not new-user CAC.", analyst="Restricted to monetary quintile 5. Recency is days since last order."),

        ],
    },
    {
        "id": "payments_checkout",
        "title": "Payments & Checkout",
        "icon": "💳",
        "lens": "Finance / Product",
        "description": "How people pay, and where checkout does not finish.",
        "questions": [
            _q("pay01", "What is the payment type mix by order count?", "payments_checkout/01_payment_mix_orders.sql",
               metrics=[("Dominant Payment Type", "orders", "max", "int"), ("Payment Types", "payment_type", "count", "int")],
               chart=("bar", "payment_type", "orders", "Orders by Payment Type"),
               product="Optimize checkout for dominant payment method.", finance="Payment mix affects settlement timing.", analyst="Distinct order_id per payment type."),
            _q("pay02", "What is the payment type mix by value?", "payments_checkout/02_payment_mix_value.sql",
               metrics=[("Total Payment Value", "total_payment_value", "sum", "currency"), ("Top Type Share", "value_share_pct", "max", "pct")],
               chart=("bar", "payment_type", "total_payment_value", "Payment Value by Type"),
               product="High-value checkout may need card-first UX.", finance="Value mix differs from count mix.", analyst="Sum payment_value from payments table."),
            _q("pay03", "Which payment types have the highest AOV?", "payments_checkout/03_payment_aov.sql",
               metrics=[("Highest Payment AOV", "avg_order_value", "max", "currency"), ("Lowest Payment AOV", "avg_order_value", "min", "currency")],
               chart=("bar", "payment_type", "avg_order_value", "AOV by Payment Type"),
               product="Promote high-AOV payment options.", finance="Credit card AOV often exceeds boleto.", analyst="Join payments to order revenue view."),
            _q("pay04", "How are installment plans distributed?", "payments_checkout/04_installments.sql",
               metrics=[("Most Common Installments", "orders", "max", "int"), ("Avg Installments", "avg_installments", "mean", "float")],
               chart=("bar", "payment_installments", "orders", "Orders by Installment Count"),
               product="Highlight 1x vs 12x options clearly.", finance="Installments affect receivables timing.", analyst="From payment_installments column."),
            _q("pay05", "How many orders use multiple payment methods?", "payments_checkout/05_multi_payment_orders.sql",
               metrics=[("Multi-Pay Orders", "multi_payment_orders", "first", "int"), ("Multi-Pay Share", "multi_payment_share_pct", "first", "pct")],
               chart=("bar", "payment_pattern", "orders", "Single vs Multi Payment"),
               product="Split-payment UX if multi-pay is common.", finance="Multi-pay may indicate partial failures.", analyst="Count payment rows per order > 1."),
            _q("pay06", "What share of orders never get approved?", "payments_checkout/06_unapproved_orders.sql",
               metrics=[("Unapproved Rate", "unapproved_rate_pct", "mean", "pct"), ("Peak Unapproved Month", "unapproved_rate_pct", "max", "pct")],
               chart=("line", "purchase_month", "unapproved_rate_pct", "Unapproved Rate by Month"),
               product="Reduce boleto friction if unapproved is high.", finance="Unapproved orders = lost revenue.", analyst="order_approved_at IS NULL proxy."),
            _q("pay07", "Which states prefer credit card vs boleto?", "payments_checkout/07_payment_by_state.sql",
               metrics=[("State-Payment Rows", "payment_type", "count", "int")],
               chart=("bar", "payment_type", "orders", "Payment Preference (top states)"),
               product="Default payment method by state.", finance="Regional payment cost structures differ.", analyst="Top 5 states filter applied."),
            _q("pay08", "Is credit card share increasing over time?", "payments_checkout/08_credit_card_trend.sql",
               metrics=[("Latest CC Share", "credit_card_share_pct", "last", "pct"), ("First CC Share", "credit_card_share_pct", "first", "pct")],
               chart=("line", "purchase_month", "credit_card_share_pct", "Credit Card Share Trend"),
               product="Invest in card tokenization if share rises.", finance="Card share affects interchange costs.", analyst="Monthly credit_card orders / total orders."),
            _q("pay09", "Do high-value orders prefer credit card?", "payments_checkout/09_high_value_payment.sql",
               metrics=[("High-Value CC Share", "credit_card_share_pct", "first", "pct"), ("Threshold GMV", "gmv_threshold", "first", "currency")],
               chart=("bar", "order_value_tier", "credit_card_share_pct", "CC Share by Order Tier"),
               product="Prioritize card rails for high-value checkout.", finance="High-value fraud checks may add friction.", analyst="Top quartile GMV orders analyzed."),
            _q("pay10", "What is average payment value by type and month?", "payments_checkout/10_payment_value_trend.sql",
               metrics=[("Highest Avg Payment", "avg_payment_value", "max", "currency")],
               chart=("line", "purchase_month", "avg_payment_value", "Avg Payment Value Trend"),
               product="Watch for payment value drops post-campaign.", finance="Payment value trend validates GMV trend.", analyst="Grouped by month and payment type."),
            _q("pay11", "Which payment types have the weakest approval conversion?", "payments_checkout/11_approval_by_type.sql",
               metrics=[("Best Approval", "approval_rate_pct", "max", "pct"), ("Weakest Approval", "approval_rate_pct", "min", "pct"), ("Payment Types", "payment_type", "count", "int")],
               chart=("bar", "payment_type", "approval_rate_pct", "Approval Conversion by Payment"),
               product="Simplify the payment type with the weakest approval rate.", finance="Failed approval is checkout revenue that never starts.", analyst="Approval = order_approved_at is present."),
            _q("pay12", "How does checkout conversion change month over month?", "payments_checkout/12_mom_checkout_conversion.sql",
               metrics=[("Latest Conversion", "conversion_pct", "last", "pct"), ("Avg Conversion", "conversion_pct", "mean", "pct"), ("Worst Change", "conversion_change_pct", "min", "pct")],
               chart=("line", "purchase_month", "conversion_pct", "Checkout Conversion Trend"),
               product="Investigate months where conversion drops, not just the average.", finance="Conversion change is a revenue variance driver.", analyst="LAG compares each month with the previous month."),
            _q("pay13", "How much GMV is stuck before payment approval each month?", "payments_checkout/13_payment_dropoff_gmv.sql",
               metrics=[("Peak Drop-off", "dropoff_pct", "max", "pct"), ("GMV at Risk", "gmv_at_risk", "sum", "currency"), ("Unapproved Orders", "unapproved_orders", "sum", "int")],
               chart=("line", "purchase_month", "dropoff_pct", "Payment Drop-off Rate"),
               product="Add a retry or reminder on the unapproved path.", finance="GMV at risk is not yet collectible.", analyst="Drop-off = orders with no approval and no later shipment."),
            _q("pay14", "Do top 20% customers convert better at checkout and delivery?", "payments_checkout/14_top20_conversion.sql",
               metrics=[("Top 20% Approval", "approval_rate_pct", "first", "pct"), ("Top 20% Delivery", "delivery_rate_pct", "first", "pct"), ("Top 20% Orders", "orders", "first", "int")],
               chart=("bar", "cohort", "approval_rate_pct", "Approval Rate by Cohort"),
               product="If the best customers convert worse, the friction is in the premium path.", finance="Compare cohort conversion before spending more on acquisition.", analyst="Cohort is the same monetary quintile used in the RFM quest."),
            _q("pay15", "Which first payment type leads to a second order?", "payments_checkout/15_repeat_by_first_payment.sql",
               metrics=[("Best Repeat Rate", "repeat_rate_pct", "max", "pct"), ("Customers", "customers", "sum", "int")],
               chart=("bar", "payment_type", "repeat_rate_pct", "Repeat Rate by First Payment"),
               product="Default new users into the payment type that retains.", finance="Payment mix is a retention lever, not only a fee lever.", analyst="First order uses ROW_NUMBER; repeat uses customer_unique_id."),

        ],
    },
    {
        "id": "logistics_reviews",
        "title": "Logistics & Reviews",
        "icon": "🚚",
        "lens": "Product / Ops",
        "description": "Where orders get stuck, and whether a late delivery hurts the review.",
        "questions": [
            _q("lr01", "What is the order status distribution?", "logistics_reviews/01_order_status.sql",
               metrics=[("Delivered Share", "share_pct", "max", "pct"), ("Canceled Orders", "orders", "last", "int")],
               chart=("bar", "order_status", "orders", "Orders by Status"),
               product="Fix statuses with high in-progress concentration.", finance="Undelivered orders delay revenue recognition.", analyst="Snapshot of current status field."),
            _q("lr02", "Does late delivery hurt review scores?", "logistics_reviews/02_delay_vs_reviews.sql",
               metrics=[("On-Time Avg Score", "avg_review_score", "max", "float"), ("Severe Delay Avg Score", "avg_review_score", "min", "float")],
               chart=("bar", "delay_bucket", "avg_review_score", "Review Score by Delay"),
               product="Priority shipping for delay-prone lanes.", finance="Bad reviews reduce repeat purchase LTV.", analyst="Delay = delivered - estimated date."),
            _q("lr03", "What is the on-time delivery rate?", "logistics_reviews/03_on_time_rate.sql",
               metrics=[("On-Time Rate", "on_time_rate_pct", "first", "pct"), ("Late Deliveries", "late_deliveries", "first", "int")],
               chart=("bar", "delivery_result", "orders", "On-Time vs Late"),
               product="Set SLA alerts when on-time drops.", finance="Late delivery increases support cost.", analyst="On-time = delay_days <= 0."),
            _q("lr04", "How many days late are deliveries on average?", "logistics_reviews/04_avg_delay_days.sql",
               metrics=[("Avg Delay Days", "avg_delay_days", "mean", "float"), ("Max Avg by State", "avg_delay_days", "max", "float")],
               chart=("bar", "customer_state", "avg_delay_days", "Avg Delay by State"),
               product="Regional carrier changes for worst states.", finance="Delay drives refunds and churn.", analyst="Only late orders (delay > 0)."),
            _q("lr05", "What is the review score distribution?", "logistics_reviews/05_review_distribution.sql",
               metrics=[("Avg Review Score", "reviews", "mean", "float"), ("5-Star Share", "share_pct", "max", "pct")],
               chart=("bar", "review_score", "reviews", "Review Score Distribution"),
               product="Investigate 1-2 star root causes.", finance="Low scores predict return/chargeback risk.", analyst="Histogram of review_score 1-5."),
            _q("lr06", "Which categories get the lowest review scores?", "logistics_reviews/06_low_score_categories.sql",
               metrics=[("Lowest Avg Score", "avg_review_score", "min", "float"), ("Categories", "category", "count", "int")],
               chart=("bar", "category", "avg_review_score", "Avg Review by Category"),
               product="Quality checks on low-rated categories.", finance="Returns hit margin on bad categories.", analyst="Join reviews → orders → items → category."),
            _q("lr07", "What share of delivered orders get reviewed?", "logistics_reviews/07_review_coverage.sql",
               metrics=[("Review Coverage", "review_coverage_pct", "first", "pct"), ("Reviewed Orders", "reviewed_orders", "first", "int")],
               chart=("bar", "month", "review_coverage_pct", "Review Coverage by Month"),
               product="Post-delivery review prompts.", finance="Low coverage hides satisfaction issues.", analyst="Reviewed / delivered orders per month."),
            _q("lr08", "How long from purchase to delivery?", "logistics_reviews/08_purchase_to_delivery.sql",
               metrics=[("Median Delivery Days", "median_delivery_days", "median", "int"), ("P90 Delivery Days", "median_delivery_days", "p90", "int")],
               chart=("bar", "delivery_days_bucket", "orders", "Purchase-to-Delivery Days"),
               product="Show delivery estimate upfront.", finance="Long delivery windows increase cancellations.", analyst="julianday diff purchase to delivered."),
            _q("lr09", "Which months had the worst delivery delays?", "logistics_reviews/09_delay_by_month.sql",
               metrics=[("Worst Month Avg Delay", "avg_delay_days", "max", "float")],
               chart=("line", "purchase_month", "avg_delay_days", "Avg Delay by Month"),
               product="Seasonal logistics capacity planning.", finance="Peak delay months need cost buffer.", analyst="Monthly avg of positive delay days."),
            _q("lr10", "Do review scores trend down over time?", "logistics_reviews/10_review_score_trend.sql",
               metrics=[("Latest Avg Score", "avg_review_score", "last", "float"), ("First Avg Score", "avg_review_score", "first", "float")],
               chart=("line", "review_month", "avg_review_score", "Avg Review Score Trend"),
               product="Ops review if scores decline.", finance="Falling scores = future retention risk.", analyst="Monthly avg review_score."),
            _q("lr11", "Where do orders drop off between purchase and delivery?", "logistics_reviews/11_delivery_funnel.sql",
               metrics=[("Delivered Conversion", "conversion_from_start_pct", "last", "pct"), ("Purchased Orders", "orders", "first", "int"), ("Biggest Stage Drop", "dropoff_from_prior_pct", "max", "pct")],
               chart=("bar", "stage", "orders", "Delivery Funnel"),
               product="The biggest stage drop is the ops fix, not a blanket 'delivery' problem.", finance="Only the Delivered stage is completed demand.", analyst="Funnel is monotonic. LAG measures drop-off from the prior stage."),
            _q("lr12", "Which months have the worst delivery drop-off?", "logistics_reviews/12_dropoff_by_month.sql",
               metrics=[("Worst Drop-off", "dropoff_pct", "max", "pct"), ("Avg Drop-off", "dropoff_pct", "mean", "pct"), ("Dropped Orders", "dropped_orders", "sum", "int")],
               chart=("line", "purchase_month", "dropoff_pct", "Delivery Drop-off by Month"),
               product="Staff carriers before the months that historically drop off.", finance="Drop-off spikes are a revenue timing risk.", analyst="Drop-off = no customer delivery timestamp."),
            _q("lr13", "Which states have the highest delivery drop-off?", "logistics_reviews/13_dropoff_by_state.sql",
               metrics=[("Worst State Drop-off", "dropoff_pct", "max", "pct"), ("GMV Lost", "gmv_lost", "sum", "currency")],
               chart=("bar", "customer_state", "dropoff_pct", "Drop-off by State"),
               product="Change the carrier or promise in the worst states.", finance="GMV lost is state-level leakage.", analyst="States with under 300 orders are hidden so tiny samples don't rank first."),
            _q("lr14", "Are delivery conversion and on-time rate improving?", "logistics_reviews/14_mom_delivery_quality.sql",
               metrics=[("Latest Delivery Conversion", "delivery_conversion_pct", "last", "pct"), ("Latest On-Time", "on_time_pct", "last", "pct"), ("Best On-Time", "on_time_pct", "max", "pct")],
               chart=("line", "purchase_month", "delivery_conversion_pct", "Delivery Conversion"), chart2=("line", "purchase_month", "on_time_pct", "On-Time Rate"),
               product="Track both completion and lateness — a delivered-but-late order still hurts retention.", finance="On-time failure shows up later as lower repeat GMV.", analyst="On-time = delivered on or before the estimated date."),
            _q("lr15", "Do top 20% customers see fewer delivery drop-offs?", "logistics_reviews/15_top20_dropoff.sql",
               metrics=[("Top 20% Drop-off", "dropoff_pct", "first", "pct"), ("Top 20% Review", "avg_review_score", "first", "float"), ("Top 20% Orders", "orders", "first", "int")],
               chart=("bar", "cohort", "dropoff_pct", "Drop-off by Value Cohort"),
               product="High-value customers should not have a worse delivery experience.", finance="A drop-off gap on this cohort is expensive churn.", analyst="Same RFM top quintile, joined to orders and reviews."),

        ],
    },
    {
        "id": "sellers_marketplace",
        "title": "Sellers & Marketplace",
        "icon": "🏪",
        "lens": "Product / Finance",
        "description": "Which sellers bring in sales, and which ones fail to deliver.",
        "questions": [
            _q("sm01", "Which sellers drive the most revenue?", "sellers_marketplace/01_seller_leaderboard.sql",
               metrics=[("Top Seller Revenue", "revenue", "max", "currency"), ("Top 20 Revenue", "revenue", "sum", "currency")],
               chart=("bar", "seller_rank", "revenue", "Top Sellers by Revenue"),
               product="Dedicated support for top sellers.", finance="Seller concentration = platform risk.", analyst="Top 20 sellers ranked."),
            _q("sm02", "How are sellers distributed across states?", "sellers_marketplace/02_sellers_by_state.sql",
               metrics=[("Top Seller State", "sellers", "max", "int"), ("States with Sellers", "seller_state", "count", "int")],
               chart=("bar", "seller_state", "sellers", "Sellers by State"),
               product="Recruit sellers in underserved states.", finance="Supply geography affects delivery times.", analyst="Distinct seller_id per state."),
            _q("sm03", "What does seller revenue concentration look like?", "sellers_marketplace/03_seller_concentration.sql",
               metrics=[("Top 10% Seller Share", "top_decile_share_pct", "first", "pct"), ("Total Sellers", "total_sellers", "first", "int")],
               chart=("bar", "segment", "revenue", "Seller Revenue Concentration"),
               product="Long-tail seller growth program.", finance="High concentration needs diversification.", analyst="Top decile by seller revenue."),
            _q("sm04", "What categories do top sellers focus on?", "sellers_marketplace/04_top_seller_categories.sql",
               metrics=[("Top Pair Revenue", "revenue", "max", "currency")],
               chart=("bar", "category", "revenue", "Top Seller Category Focus"),
               product="Category-specific seller onboarding.", finance="Category concentration per seller.", analyst="Top 10 sellers only."),
            _q("sm05", "What is the average revenue per seller?", "sellers_marketplace/05_avg_seller_revenue.sql",
               metrics=[("Avg Seller Revenue", "revenue", "mean", "currency"), ("Median Seller Revenue", "revenue", "median", "currency")],
               chart=("bar", "revenue_bucket", "sellers", "Sellers by Revenue Bucket"),
               product="Help mid-tier sellers grow GMV.", finance="Mean vs median shows skew.", analyst="Bucketed seller revenue histogram."),
            _q("sm06", "Which sellers have the highest freight charges?", "sellers_marketplace/06_seller_freight.sql",
               metrics=[("Highest Seller Freight", "freight_revenue", "max", "currency"), ("Total Freight", "freight_revenue", "sum", "currency")],
               chart=("bar", "seller_id", "freight_revenue", "Top Sellers by Freight"),
               product="Shipping optimization for heavy sellers.", finance="Freight affects seller payouts.", analyst="Top 15 sellers by freight."),
            _q("sm07", "How many orders involve multiple sellers?", "sellers_marketplace/07_multi_seller_orders.sql",
               metrics=[("Multi-Seller Orders", "multi_seller_orders", "first", "int"), ("Multi-Seller Share", "multi_seller_share_pct", "first", "pct")],
               chart=("bar", "order_type", "orders", "Single vs Multi-Seller Orders"),
               product="Split-shipment UX for multi-seller carts.", finance="Multi-seller increases logistics cost.", analyst="Distinct sellers per order > 1."),
            _q("sm08", "Which seller cities dominate GMV?", "sellers_marketplace/08_seller_city_gmv.sql",
               metrics=[("Top City GMV", "revenue", "max", "currency")],
               chart=("bar", "seller_city", "revenue", "GMV by Seller City"),
               product="Hub-based fulfillment near top cities.", finance="City clusters reduce last-mile cost.", analyst="Top 15 seller cities."),
            _q("sm09", "How many sellers are long-tail (low revenue)?", "sellers_marketplace/09_long_tail_sellers.sql",
               metrics=[("Long-Tail Sellers", "sellers", "first", "int"), ("Long-Tail Share", "seller_share_pct", "first", "pct")],
               chart=("bar", "seller_tier", "sellers", "Seller Tiers by Count"),
               product="Enable tools for long-tail seller success.", finance="Long-tail may have higher ops cost per GMV.", analyst="Bottom 80% by revenue = long tail."),
            _q("sm10", "What is avg order value by top sellers?", "sellers_marketplace/10_seller_aov.sql",
               metrics=[("Highest Seller AOV", "avg_order_value", "max", "currency"), ("Avg Top-20 AOV", "avg_order_value", "mean", "currency")],
               chart=("bar", "seller_rank", "avg_order_value", "AOV — Top Sellers"),
               product="Premium sellers may need premium checkout.", finance="High-AOV sellers drive margin.", analyst="Top 20 sellers by revenue."),
            _q("sm11", "Which sellers create the most delivery drop-off?", "sellers_marketplace/11_seller_dropoff.sql",
               metrics=[("Worst Drop-off", "dropoff_pct", "max", "pct"), ("GMV Lost", "gmv_lost", "sum", "currency"), ("Sellers Shown", "seller_label", "count", "int")],
               chart=("bar", "seller_label", "gmv_lost", "GMV Lost by Seller"),
               product="Coach or throttle sellers who fail to deliver.", finance="Their GMV lost is marketplace leakage.", analyst="Seller must have at least 80 orders. Ranked by GMV lost."),
            _q("sm12", "What is month-over-month seller retention?", "sellers_marketplace/12_seller_mom_retention.sql",
               metrics=[("Latest Seller Retention", "mom_retention_pct", "last", "pct"), ("Avg Retention", "mom_retention_pct", "mean", "pct"), ("Best Retention", "mom_retention_pct", "max", "pct")],
               chart=("line", "month", "mom_retention_pct", "Seller MoM Retention"),
               product="A seller who disappears is a supply problem for next month's conversion.", finance="Seller churn reduces available GMV.", analyst="Retained = sold this month and the previous month."),
            _q("sm13", "Which sellers serve the top 20% high-value cohort?", "sellers_marketplace/13_top20_sellers.sql",
               metrics=[("Top Seller Revenue", "revenue", "max", "currency"), ("Listed Revenue", "revenue", "sum", "currency")],
               chart=("bar", "seller_label", "revenue", "Sellers of the Top 20%"),
               product="Protect the relationship with sellers this cohort already trusts.", finance="This is the supply base behind high-value GMV.", analyst="Joined from the RFM monetary quintile to order items."),
            _q("sm14", "Which seller states convert shipped orders to delivered the worst?", "sellers_marketplace/14_state_ship_conversion.sql",
               metrics=[("Lowest Conversion", "conversion_pct", "min", "pct"), ("States Shown", "seller_state", "count", "int")],
               chart=("bar", "seller_state", "conversion_pct", "Shipped-to-Delivered by Seller State"),
               product="Last-mile fixes should start in the worst seller states.", finance="Shipped but not delivered is cost without revenue.", analyst="Conversion = delivered orders / shipped orders, minimum 200 shipped."),
            _q("sm15", "Which sellers are best at bringing customers back?", "sellers_marketplace/15_seller_repeat_rate.sql",
               metrics=[("Best Repeat Rate", "repeat_rate_pct", "max", "pct"), ("Sellers Shown", "seller_label", "count", "int")],
               chart=("bar", "seller_label", "repeat_rate_pct", "Seller Repeat Rate"),
               product="Study what high-repeat sellers do and copy it into onboarding.", finance="Repeat rate is a seller-quality metric, not just a GMV rank.", analyst="Repeat = the same customer_unique_id orders from that seller twice."),

        ],
    },
]


def get_category(category_id: str) -> QuestCategory | None:
    return next((c for c in QUEST_CATEGORIES if c["id"] == category_id), None)
